### ISSUE TITLE
65ms delay needed between setChannel and next readout.

### ISSUE THREAD

**Issue by FunDeckHermit** [RobTillaart/MCP3424#4]
This is not really a bug, more of a general tip for anyone struggling to change channels on the MCP3428 with this library.
You need a delay of around **65ms** between setting a channel and reading the value.

**Comment by RobTillaart** [comment]
Thanks for reporting this issue.

Can you pinpoint the place in the datasheet where this is mentioned?

This should be in the documentation / comments .h file in my opinion.
It would not be nice to block for 65 milliseconds. 

Would you like a function like **readyForRead()** to check the last channel switch?
Track timestamp of last channel switch (real change only so switching twice to channel 0 is no switch. and single channel>
Think that is a bit overkill

**Comment by RobTillaart** [comment]
Think the best place is to mention it near the Resolution and SPS (samples per second) as the 65 ms is about the time when getting 15 SPS => 66.6 ms

something like this

|  Bits  |  LSB (gain=1)  |  SPS   |  Interval  |     Raw range       |  Notes  |
|:------:|---------------:|:------:|:----------:|:-------------------:|:-------:|
|   12   |          1 mV  |  240   |    4.2 ms  |    -2048 .. 2047    |
|   14   |        250 µV  |   60   |   16.7 ms  |    -8192 .. 8191    |
|   16   |       62.5 µV  |   15   |   66.7 ms  |   -32768 .. 32767   |
|   18   |     15.625 µV  |  3.75  |  266.7 ms  |  -131072 .. 131071  |  not for 3426/27/28.

**Comment by RobTillaart** [comment]
@FunDeckHermit 

Can you run **MCP3424_performance.ino** and post output + board used?
(patched for your ADC of course).

**Comment by FunDeckHermit** [comment]
Hi Rob,

The 65ms was empirically deduced by adding delays everywhere in my code and reducing/removing them gradually.

I'm running on 16bit resolution so the SPS of 15 seems like the culprit here. 

Maybe add an example where you start a timer that waits 70ms for the read()? To show inexperienced programmers what would be best practice. 

In my case I'm running on an ESP32 in a task, delays are actually just task switchers.

Next Tuesday I'm back at the office to test the performance.ino. Do you have the MCP3428 laying around? I can send you a breadboard friendly module if you happen to live in The Netherlands.

**Comment by RobTillaart** [comment]
> Maybe add an example where you start a timer that waits 70ms for the read()? To show inexperienced programmers what would be best practice.

Good idea,

> Do you have the MCP3428 laying around? I can send you a breadboard friendly module if you happen to live in The Netherlands.

No, Yes would be appreciated!

My email is rob.tillaart@gmail.com, please mail me for my address.

**Comment by RobTillaart** [comment]
@FunDeckHermit 

How about a function **uint16_t getInterval()** which based upon the resolution returns the nr of millis to wait for read?

```cpp
uint16_t getInterval()
{
  uint16_t  _interval[4] = { 5, 17, 67, 267 };
  int idx = (_resolution - 12) / 2;  //  12-> 0 ... 18-> 3
  return _interval[idx];
}
```

**Comment by RobTillaart** [comment]
Example, something like this?

```cpp
//
//    FILE: MCP3428_setChannel.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: demo to show the needed timeout between setChannel() and read()
//     URL: https://github.com/RobTillaart/MCP3424

#include "MCP3424.h"

MCP3428 mcp;


void setup()
{
  Serial.begin(115200);
  Serial.println();
  Serial.println(__FILE__);
  Serial.print("MCP3424_LIB_VERSION: ");
  Serial.println(MCP3424_LIB_VERSION);
  Serial.println();

  Wire.begin();
  Wire.setTimeout(10000);

  mcp.begin();

  //  dump configuration
  Serial.println();
  Serial.print("Address:\t");
  Serial.println(mcp.getAddress(), HEX);
  Serial.print("Connect:\t");
  Serial.println(mcp.isConnected());
  Serial.print("Channels:\t");
  Serial.println(mcp.getMaxChannels());
  Serial.print("Gain:\t");
  Serial.println(mcp.getGain());
  Serial.print("Bits:\t");
  Serial.println(mcp.getResolution());
  Serial.print("Mode:\t");
  Serial.println(mcp.getMode());
  Serial.println();

}


void loop()
{
  for (int chan = 0; chan < mcp.getMaxChannels(); chan++)
  {
    mcp.setChannel(chan);
    //  new measurement duration depends on resolution. See readme.md.
    delay(67);
    Serial.print(mcp.read());
    Serial.print("\t");
    Serial.println(mcp.readVolts(), 6);
  }
}


//  -- END OF FILE --
```

**Comment by FunDeckHermit** [comment]
Yea, that looks fine. I would rename `getInterval` to `getConversionDelayInterval` or something like that to make it more explicit. 

I'll contact you over email for the address!

**Comment by RobTillaart** [comment]
Thanks for the name proposal, ```getConversionDelay``` would be long and clear enough ?

**Comment by RobTillaart** [comment]
@FunDeckHermit 

Merged the develop branch so this issue is closed. 
If there are other problems or possible enhancements to improve this (or any) library please open a new issue.

Again thanks for reporting, appreciated!
